/**
 * Skill taxonomy for resume parsing.
 * ~500 terms across 15 categories, plus abbreviation map and job title patterns.
 */

export const SKILL_CATEGORIES: Record<string, string[]> = {
  "Programming Languages": [
    "JavaScript",
    "TypeScript",
    "Python",
    "Java",
    "C#",
    "C++",
    "Ruby",
    "PHP",
    "Swift",
    "Kotlin",
    "Rust",
    "Scala",
    "Perl",
    "Haskell",
    "Elixir",
    "Clojure",
    "Erlang",
    "Lua",
    "Dart",
    "Objective-C",
    "MATLAB",
    "Assembly",
    "COBOL",
    "Fortran",
    "Julia",
    "Groovy",
    "F#",
    "OCaml",
    "Zig",
    "V",
    "Nim",
    "Crystal",
    "Solidity",
    "VHDL",
    "Verilog",
  ],
  "Frontend Frameworks": [
    "React",
    "Angular",
    "Vue.js",
    "Svelte",
    "Next.js",
    "Nuxt.js",
    "Gatsby",
    "Remix",
    "Astro",
    "SolidJS",
    "Ember.js",
    "Backbone.js",
    "Alpine.js",
    "Lit",
    "Preact",
    "Qwik",
    "htmx",
  ],
  "Backend Frameworks": [
    "Node.js",
    "Express",
    "Express.js",
    "NestJS",
    "Fastify",
    "Django",
    "Flask",
    "FastAPI",
    "Spring Boot",
    "Spring",
    "Ruby on Rails",
    "Rails",
    "Laravel",
    "Symfony",
    "ASP.NET",
    ".NET",
    "Gin",
    "Echo",
    "Fiber",
    "Phoenix",
    "Actix",
    "Rocket",
    "Hono",
    "Koa",
  ],
  Databases: [
    "PostgreSQL",
    "MySQL",
    "SQLite",
    "MongoDB",
    "Redis",
    "Elasticsearch",
    "DynamoDB",
    "Cassandra",
    "CouchDB",
    "Neo4j",
    "MariaDB",
    "Oracle Database",
    "SQL Server",
    "Firestore",
    "Supabase",
    "PlanetScale",
    "CockroachDB",
    "InfluxDB",
    "TimescaleDB",
    "Memcached",
    "RabbitMQ",
    "Apache Kafka",
    "Kafka",
    "Prisma",
    "Drizzle",
    "Sequelize",
    "TypeORM",
    "Mongoose",
    "Knex",
  ],
  "Cloud & DevOps": [
    "AWS",
    "Amazon Web Services",
    "Azure",
    "Google Cloud",
    "GCP",
    "Docker",
    "Kubernetes",
    "Terraform",
    "Ansible",
    "Jenkins",
    "GitHub Actions",
    "GitLab CI",
    "CircleCI",
    "Travis CI",
    "Vercel",
    "Netlify",
    "Heroku",
    "DigitalOcean",
    "Cloudflare",
    "Nginx",
    "Apache",
    "Linux",
    "Ubuntu",
    "CentOS",
    "Helm",
    "Pulumi",
    "Vagrant",
    "Packer",
    "ArgoCD",
    "Prometheus",
    "Grafana",
    "Datadog",
    "New Relic",
    "ELK Stack",
    "Splunk",
  ],
  "AWS Services": [
    "EC2",
    "S3",
    "Lambda",
    "RDS",
    "ECS",
    "EKS",
    "CloudFront",
    "Route 53",
    "SQS",
    "SNS",
    "API Gateway",
    "CloudWatch",
    "IAM",
    "VPC",
    "CloudFormation",
    "Step Functions",
    "Cognito",
    "SES",
    "Kinesis",
    "Redshift",
    "Athena",
    "Glue",
    "SageMaker",
    "Bedrock",
  ],
  "CSS & Styling": [
    "CSS",
    "Sass",
    "SCSS",
    "Less",
    "Tailwind CSS",
    "Bootstrap",
    "Material UI",
    "Chakra UI",
    "Styled Components",
    "CSS Modules",
    "PostCSS",
    "CSS-in-JS",
    "Ant Design",
    "Radix UI",
    "shadcn/ui",
    "Headless UI",
  ],
  "Testing & QA": [
    "Jest",
    "Vitest",
    "Mocha",
    "Cypress",
    "Playwright",
    "Selenium",
    "Puppeteer",
    "Testing Library",
    "React Testing Library",
    "Enzyme",
    "PyTest",
    "JUnit",
    "RSpec",
    "PHPUnit",
    "Storybook",
    "Chromatic",
    "Percy",
    "k6",
    "Locust",
    "Artillery",
    "SonarQube",
    "ESLint",
    "Prettier",
  ],
  "Mobile Development": [
    "React Native",
    "Flutter",
    "Expo",
    "SwiftUI",
    "UIKit",
    "Jetpack Compose",
    "Android SDK",
    "iOS",
    "Android",
    "Xamarin",
    "Ionic",
    "Capacitor",
    "Cordova",
    "NativeScript",
  ],
  "AI & Machine Learning": [
    "TensorFlow",
    "PyTorch",
    "Keras",
    "scikit-learn",
    "OpenCV",
    "NLTK",
    "spaCy",
    "Hugging Face",
    "LangChain",
    "OpenAI",
    "GPT",
    "LLM",
    "Machine Learning",
    "Deep Learning",
    "Natural Language Processing",
    "NLP",
    "Computer Vision",
    "Reinforcement Learning",
    "MLOps",
    "MLflow",
    "Kubeflow",
    "Pandas",
    "NumPy",
    "SciPy",
    "Matplotlib",
    "Jupyter",
    "Databricks",
    "Apache Spark",
    "Spark",
    "Hadoop",
    "Airflow",
  ],
  "API & Integration": [
    "REST",
    "RESTful",
    "GraphQL",
    "gRPC",
    "WebSocket",
    "WebSockets",
    "SOAP",
    "OAuth",
    "OAuth2",
    "JWT",
    "OpenAPI",
    "Swagger",
    "Postman",
    "tRPC",
    "Apollo",
    "Axios",
    "Fetch API",
    "Webhook",
    "Webhooks",
    "SSE",
    "Server-Sent Events",
  ],
  "Version Control & Tools": [
    "Git",
    "GitHub",
    "GitLab",
    "Bitbucket",
    "SVN",
    "Jira",
    "Confluence",
    "Notion",
    "Linear",
    "Figma",
    "Sketch",
    "Adobe XD",
    "VS Code",
    "IntelliJ",
    "Vim",
    "Webpack",
    "Vite",
    "Rollup",
    "esbuild",
    "Parcel",
    "Turbopack",
    "Babel",
    "SWC",
    "npm",
    "yarn",
    "pnpm",
    "Bun",
    "Deno",
  ],
  "Data & Analytics": [
    "SQL",
    "NoSQL",
    "ETL",
    "Data Warehousing",
    "Data Modeling",
    "Data Pipeline",
    "Business Intelligence",
    "Tableau",
    "Power BI",
    "Looker",
    "dbt",
    "Snowflake",
    "BigQuery",
    "Data Lake",
    "Apache Flink",
    "Apache Beam",
  ],
  "Security & Auth": [
    "Cybersecurity",
    "Penetration Testing",
    "OWASP",
    "SSL/TLS",
    "Encryption",
    "SSO",
    "SAML",
    "LDAP",
    "Active Directory",
    "Auth0",
    "Okta",
    "Keycloak",
    "Vault",
    "HashiCorp",
  ],
  "Methodologies & Practices": [
    "Agile",
    "Scrum",
    "Kanban",
    "CI/CD",
    "DevOps",
    "SRE",
    "TDD",
    "BDD",
    "DDD",
    "Microservices",
    "Monorepo",
    "Serverless",
    "Event-Driven",
    "CQRS",
    "Design Patterns",
    "System Design",
    "Clean Architecture",
    "Twelve-Factor",
    "Pair Programming",
    "Code Review",
    "Technical Writing",
  ],
};

/** Abbreviation → full form mapping for expansion. */
export const ABBREVIATION_MAP: Record<string, string> = {
  JS: "JavaScript",
  TS: "TypeScript",
  PG: "PostgreSQL",
  k8s: "Kubernetes",
  RN: "React Native",
  ML: "Machine Learning",
  DL: "Deep Learning",
  AI: "Artificial Intelligence",
  CI: "Continuous Integration",
  CD: "Continuous Deployment",
  DB: "Database",
  API: "Application Programming Interface",
  SPA: "Single Page Application",
  SSR: "Server-Side Rendering",
  SSG: "Static Site Generation",
  ORM: "Object-Relational Mapping",
  CMS: "Content Management System",
  IDE: "Integrated Development Environment",
};

/** Short terms that need stricter matching (surrounded by boundaries or in specific contexts). */
export const SHORT_TERMS = new Set([
  "R",
  "C",
  "Go",
  "V",
  "Nim",
  "Lit",
  "k6",
  "Bun",
  "Vim",
  "Git",
  "SQL",
  "CSS",
  "dbt",
  "Zig",
  "Gin",
  "Koa",
  "SWC",
  "npm",
  "SSE",
  "JWT",
  "SSO",
  "ETL",
  "SRE",
  "TDD",
  "BDD",
  "DDD",
  "IAM",
  "VPC",
  "EC2",
  "S3",
  "SQS",
  "SNS",
  "SES",
  "RDS",
  "ECS",
  "EKS",
  "GCP",
  "AWS",
  "NLP",
  "LLM",
  "GPT",
]);

/** Common job title patterns for extraction. */
export const JOB_TITLE_PATTERNS = [
  /\b(Senior|Sr\.?|Junior|Jr\.?|Lead|Staff|Principal|Associate|Mid[- ]?Level)\s+(Software|Full[- ]?Stack|Front[- ]?End|Back[- ]?End|DevOps|Cloud|Data|ML|Machine Learning|Platform|Mobile|iOS|Android|QA|Test|Security|Infrastructure|Site Reliability)\s+(Engineer|Developer|Architect|Manager|Analyst|Scientist|Consultant)\b/gi,
  /\b(Software|Full[- ]?Stack|Front[- ]?End|Back[- ]?End|DevOps|Cloud|Data|ML|Machine Learning|Platform|Mobile|iOS|Android|QA|Test|Security|Infrastructure|Site Reliability)\s+(Engineer|Developer|Architect|Manager|Analyst|Scientist|Consultant)\b/gi,
  /\b(Engineering|Technical|Tech|Development)\s+(Manager|Director|Lead|VP)\b/gi,
  /\b(CTO|VP of Engineering|Head of Engineering|Director of Engineering)\b/gi,
  /\b(Product Manager|Project Manager|Scrum Master|Technical Program Manager|TPM)\b/gi,
  /\bUI\/?UX\s+(Designer|Developer|Engineer)\b/gi,
];

/** Get all skills as a flat array. */
export function getAllSkills(): string[] {
  return Object.values(SKILL_CATEGORIES).flat();
}
